name: SonarCloud CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  build-and-analyze:
    name: Build, Test & SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      # Checkout completo do repositório
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # necessário para histórico SCM completo e cobertura de PRs

      # Configura JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Cache do Maven
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Cache do SonarCloud
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      # Build e execução dos testes (Jacoco XML)
      - name: Build and run tests
        run: mvn clean verify

      # Análise SonarCloud usando Maven
      - name: SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar \
          -Dsonar.projectKey=arthsdev_cidadao-alerta \
          -Dsonar.organization=arthsdev \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.java.binaries=target/classes \
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
          -Dsonar.verbose=true \
          -Dsonar.pullrequest.key=${{ github.event.pull_request.number || '' }} \
          -Dsonar.pullrequest.branch=${{ github.head_ref || github.ref_name }} \
          -Dsonar.pullrequest.base=${{ github.base_ref || 'main' }}
