name: SonarCloud Analysis

on:
  push:
    branches: [ '**' ]  # roda para qualquer branch
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      # 1. Pega o código
      - uses: actions/checkout@v3

      # 2. Configura JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      # 3. Cache Maven
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      # 4. Build e testes (gera cobertura Jacoco)
      - name: Build and run tests
        run: mvn clean verify

      # 5. SonarCloud analysis via Maven
      - name: Run SonarCloud analysis
        run: |
          mvn sonar:sonar \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.verbose=true \
            $([[ ${{ github.event_name }} == 'pull_request' ]] && echo "-Dsonar.pullrequest.key=${{ github.event.pull_request.number }} -Dsonar.pullrequest.branch=${{ github.head_ref }} -Dsonar.pullrequest.base=${{ github.base_ref }}")
